WITH TOTAL_SPENDING AS(
    SELECT  CUST_ID,
            CALENDAR_DT, 
          SUM(AMT_LE ) OVER(PARTITION BY CUST_ID ORDER BY CALENDAR_DT) AS TOTAL,
          ROW_NUMBER() OVER(PARTITION BY CUST_ID ORDER BY CALENDAR_DT) AS TRANSACTION_NUMBER,
          MIN(CALENDAR_DT) OVER(PARTITION BY CUST_ID) FIRST_DATE
    FROM CUSTOMERS   
)

SELECT AVG(CALENDAR_DT- FIRST_DATE) AS AVG_DAYS, AVG(TRANS) AS AVG_TRANSACTIONS
FROM 
 (
    SELECT  CUST_ID, MIN(CALENDAR_DT) CALENDAR_DT, FIRST_DATE, MIN(TRANSACTION_NUMBER) AS TRANS
    FROM 
        TOTAL_SPENDING
    WHERE 
        TOTAL IN (SELECT MIN(TOTAL) FROM TOTAL_SPENDING WHERE TOTAL >=250 GROUP BY CUST_ID ) 
    GROUP BY 
        CUST_ID, FIRST_DATE 
 )

