WITH PURCHASE_DAYS AS (
    SELECT 
        CUST_ID,
        CALENDAR_DT,
        ROW_NUMBER() OVER (PARTITION BY CUST_ID ORDER BY CALENDAR_DT) AS RN,
        CALENDAR_DT - ROW_NUMBER() OVER (PARTITION BY CUST_ID ORDER BY CALENDAR_DT) AS GRP
    FROM 
        CUSTOMERS
    WHERE 
        AMT_LE > 0
)
SELECT DISTINCT CUST_ID, MAX(CONSECUTIVE_DAYS) OVER (PARTITION BY CUST_ID) AS MAX_CONSECUTIVE_DAYS
FROM
(SELECT 
    CUST_ID, GRP,
    ROW_NUMBER() OVER (PARTITION BY CUST_ID, GRP ORDER BY CALENDAR_DT) AS CONSECUTIVE_DAYS
FROM 
    PURCHASE_DAYS)
ORDER BY CUST_ID;

















 
